"""Validate CodeCortex against indexes produced by real language indexers.

The fixtures under ``tests/fixtures/real_index`` were generated by pinned
upstream indexers and validated with the official CLI (``scip lint`` clean,
``scip print --json`` committed as ``expected.json``). Each project's
``PROVENANCE.json`` records the exact generator commit, command, and digests;
``scripts/regenerate_real_index_fixtures.sh`` reproduces them.

The tests compare CodeCortex's own decode against the official decode, and then
assert the navigation behaviour those indexes actually require. Synthetic
fixtures cannot do this job: every interesting property here — undeclared
position encodings, UTF-16 columns from a Python indexer, ``local`` ids reused
across documents, the compact range encoding — is a real indexer's behaviour
that a hand-built fixture would have had to guess.
"""

from __future__ import annotations

import hashlib
import json
from dataclasses import dataclass
from pathlib import Path

import pytest

from codecortex.config import CortexConfig
from codecortex.evidence.models import EvidenceKind, TrustTier
from codecortex.precision.compatibility import EncodingSource
from codecortex.precision.importer import import_index
from codecortex.precision.models import PrecisionIndex, PrecisionOccurrence
from codecortex.precision.positions import protocol_to_character
from codecortex.precision.provider import PrecisionEvidenceProvider, PrecisionQuery
from codecortex.precision.schema import PositionEncoding, SymbolRole

FIXTURE_ROOT = Path(__file__).resolve().parent / "fixtures" / "real_index"


@dataclass(frozen=True, slots=True)
class RealIndex:
    """One committed real index, with its oracle output and provenance."""

    name: str
    directory: Path

    @property
    def manifest(self) -> dict[str, object]:
        payload: dict[str, object] = json.loads(
            (self.directory / "PROVENANCE.json").read_text(encoding="utf-8")
        )
        return payload

    @property
    def payload(self) -> bytes:
        return (self.directory / "index.scip").read_bytes()

    @property
    def official(self) -> dict[str, object]:
        """The official CLI's decode of the same bytes."""
        decoded: dict[str, object] = json.loads(
            (self.directory / "expected.json").read_text(encoding="utf-8")
        )
        return decoded

    def imported(self) -> PrecisionIndex:
        return import_index(self.payload)


PYTHON = RealIndex("python", FIXTURE_ROOT / "python_project")
TYPESCRIPT = RealIndex("typescript", FIXTURE_ROOT / "typescript_project")
INDEXES = (PYTHON, TYPESCRIPT)
IDS = [item.name for item in INDEXES]


# -- provenance -------------------------------------------------------------


@pytest.mark.parametrize("fixture", INDEXES, ids=IDS)
def test_committed_index_matches_its_provenance_manifest(fixture: RealIndex) -> None:
    """A fixture edited by hand rather than regenerated must fail here."""
    manifest = fixture.manifest
    assert hashlib.sha256(fixture.payload).hexdigest() == manifest["index_hash"]
    expected_bytes = (fixture.directory / "expected.json").read_bytes()
    assert hashlib.sha256(expected_bytes).hexdigest() == manifest["expected_json_hash"]
    assert manifest["oracle"] == {
        "tool": "scip",
        "repository": "https://github.com/scip-code/scip",
        "commit": "1c2b6db7e560d5233c944f36e4ac1377cc6963fc",
        "lint": "clean",
        "expected_json_command": "scip print --json index.scip",
    }


@pytest.mark.parametrize("fixture", INDEXES, ids=IDS)
def test_the_recorded_generator_produced_the_committed_index(fixture: RealIndex) -> None:
    manifest = fixture.manifest
    tool = fixture.imported()
    assert tool.tool_name == manifest["generator_tool"]
    assert tool.tool_version == manifest["generator_version"]


# -- CodeCortex decode versus the official decode ---------------------------


def _official_range(occurrence: dict[str, object]) -> tuple[int, int, int, int]:
    """Normalise the official CLI's range shapes into (sl, sc, el, ec)."""
    compact = occurrence.get("range")
    if isinstance(compact, list) and len(compact) == 3:
        return compact[0], compact[1], compact[0], compact[2]
    if isinstance(compact, list) and len(compact) == 4:
        return compact[0], compact[1], compact[2], compact[3]
    typed = occurrence.get("TypedRange") or {}
    assert isinstance(typed, dict)
    single = typed.get("single_line_range")
    if isinstance(single, dict):
        line = single.get("line", 0)
        return line, single.get("start_character", 0), line, single.get("end_character", 0)
    multi = typed.get("multi_line_range")
    assert isinstance(multi, dict), occurrence
    return (
        multi.get("start_line", 0),
        multi.get("start_character", 0),
        multi.get("end_line", 0),
        multi.get("end_character", 0),
    )


def _codecortex_range(occurrence: PrecisionOccurrence) -> tuple[int, int, int, int]:
    span = occurrence.range
    return span.start_line, span.start_column, span.end_line, span.end_column


@pytest.mark.parametrize("fixture", INDEXES, ids=IDS)
def test_document_set_agrees_with_the_official_decode(fixture: RealIndex) -> None:
    official = [
        document["relative_path"]
        for document in fixture.official["documents"]  # type: ignore[index,union-attr]
    ]
    assert list(fixture.imported().paths()) == official


@pytest.mark.parametrize("fixture", INDEXES, ids=IDS)
def test_every_occurrence_agrees_with_the_official_decode(fixture: RealIndex) -> None:
    """Symbol, range, and roles must match the reference implementation exactly."""
    imported = fixture.imported()
    documents = fixture.official["documents"]
    assert isinstance(documents, list)
    for official_document in documents:
        path = official_document["relative_path"]
        document = imported.document(path)
        assert document is not None, path
        official_occurrences = [
            (item["symbol"], _official_range(item), item.get("symbol_roles", 0))
            for item in official_document["occurrences"]
        ]
        ours = [
            (item.symbol, _codecortex_range(item), item.roles)
            for item in document.occurrences
        ]
        assert ours == official_occurrences, path


@pytest.mark.parametrize("fixture", INDEXES, ids=IDS)
def test_symbol_metadata_agrees_with_the_official_decode(fixture: RealIndex) -> None:
    imported = fixture.imported()
    documents = fixture.official["documents"]
    assert isinstance(documents, list)
    for official_document in documents:
        document = imported.document(official_document["relative_path"])
        assert document is not None
        official_symbols = [
            item["symbol"] for item in official_document.get("symbols") or []
        ]
        assert [item.symbol for item in document.symbols] == official_symbols


@pytest.mark.parametrize("fixture", INDEXES, ids=IDS)
def test_relationships_agree_with_the_official_decode(fixture: RealIndex) -> None:
    imported = fixture.imported()
    official_edges: set[tuple[str, str]] = set()
    documents = fixture.official["documents"]
    assert isinstance(documents, list)
    for official_document in documents:
        for item in official_document.get("symbols") or []:
            for relationship in item.get("relationships") or []:
                if relationship.get("is_implementation"):
                    official_edges.add((item["symbol"], relationship["symbol"]))
    ours = {
        (item.symbol, relationship.symbol)
        for document in imported.documents
        for item in document.symbols
        for relationship in item.relationships
        if relationship.is_implementation
    }
    assert ours == official_edges


@pytest.mark.parametrize("fixture", INDEXES, ids=IDS)
def test_external_symbols_agree_with_the_official_decode(fixture: RealIndex) -> None:
    official = [
        item["symbol"] for item in (fixture.official.get("external_symbols") or [])
    ]
    assert [item.symbol for item in fixture.imported().external_symbols] == official


@pytest.mark.parametrize("fixture", INDEXES, ids=IDS)
def test_project_root_agrees_with_the_official_decode(fixture: RealIndex) -> None:
    metadata = fixture.official["metadata"]
    assert isinstance(metadata, dict)
    raw = metadata["project_root"]
    # The official decode reports the raw URI; CodeCortex decodes it to a path.
    assert raw.startswith("file://")
    assert fixture.imported().project_root == raw.removeprefix("file://")


# -- what these real indexes actually do ------------------------------------


@pytest.mark.parametrize("fixture", INDEXES, ids=IDS)
def test_real_indexers_declare_no_position_encoding(fixture: RealIndex) -> None:
    """Both pinned indexers omit the field the schema tells them to set.

    This is why the unspecified case cannot be treated as a rare edge: it is
    what every document in both real indexes looks like.
    """
    for document in fixture.imported().documents:
        assert document.declared_encoding is PositionEncoding.UNSPECIFIED


@pytest.mark.parametrize("fixture", INDEXES, ids=IDS)
def test_measured_encoding_is_applied_to_real_indexes(fixture: RealIndex) -> None:
    for document in fixture.imported().documents:
        assert document.encoding_source is EncodingSource.MEASURED
        assert document.position_encoding is PositionEncoding.UTF16_CODE_UNIT
        assert document.encoding_authoritative


UNICODE_LINES = {
    "python": ("app/auth.py", "user"),
    "typescript": ("src/auth.ts", "user"),
}


@pytest.mark.parametrize("fixture", INDEXES, ids=IDS)
def test_real_columns_are_utf16_not_code_points(fixture: RealIndex) -> None:
    """Re-derive the compatibility table's measurement from the committed index.

    A wrong entry in ``compatibility.MEASURED_INDEXERS`` fails here rather than
    silently shifting every column on a non-ASCII line.
    """
    path, needle = UNICODE_LINES[fixture.name]
    imported = fixture.imported()
    source = (fixture.directory / path).read_text(encoding="utf-8").splitlines()
    line_number = next(
        index
        for index, text in enumerate(source)
        if not text.isascii() and needle in text
    )
    line = source[line_number]
    character_column = line.index(needle)
    utf16 = sum(2 if ord(char) > 0xFFFF else 1 for char in line[:character_column])
    utf8 = len(line[:character_column].encode("utf-8"))
    # The three candidate encodings must actually disagree here, or the test
    # would pass for the wrong reason.
    assert len({character_column, utf16, utf8}) == 3

    document = imported.document(path)
    assert document is not None
    emitted = [
        item.range.start_column
        for item in document.occurrences
        if item.range.start_line == line_number
        and item.range.end_column - item.range.start_column == len(needle)
    ]
    assert utf16 in emitted, (line, character_column, utf16, utf8, emitted)
    assert character_column not in emitted

    converted = protocol_to_character(line, utf16, document.position_encoding)
    assert converted.column == character_column


@pytest.mark.parametrize("fixture", INDEXES, ids=IDS)
def test_real_indexes_reuse_local_ids_across_documents(fixture: RealIndex) -> None:
    """The collision this hardening fixes is what real indexers actually emit."""
    imported = fixture.imported()
    per_document = {
        document.relative_path: {
            item.symbol
            for item in document.occurrences
            if item.symbol.startswith("local ")
        }
        for document in imported.documents
    }
    populated = [names for names in per_document.values() if names]
    assert len(populated) >= 2
    shared = set.intersection(*populated)
    assert shared, per_document

    # Each shared id must resolve only within the document that declares it.
    for local in sorted(shared):
        owners = [path for path, names in per_document.items() if local in names]
        assert len(owners) >= 2
        for owner in owners:
            paths = {item.path for item in imported.occurrences_for(local, owner)}
            assert paths == {owner}
        assert imported.occurrences_for(local) == ()


def test_python_duplicate_function_names_resolve_by_identity(tmp_path: Path) -> None:
    """Two modules export session_token; only the symbol identity separates them."""
    provider = _provider(PYTHON, tmp_path)
    index = PYTHON.imported()
    definitions = {
        item.symbol: item.path
        for document in index.documents
        for item in document.occurrences
        if item.is_definition and item.symbol.endswith("session_token().")
    }
    assert len(definitions) == 2
    assert set(definitions.values()) == {"app/auth.py", "app/billing.py"}

    for symbol, path in definitions.items():
        bundle = provider.evidence_for_symbol(symbol, EvidenceKind.DEFINITION)
        assert [record.path for record in bundle.records] == [path]
        assert all(record.trust is TrustTier.EXACT for record in bundle.records)


def test_typescript_interface_implementations_are_reported(tmp_path: Path) -> None:
    """Implementation direction comes from the relationship, not from names."""
    index = TYPESCRIPT.imported()
    edges = {
        (item.symbol, relationship.symbol)
        for document in index.documents
        for item in document.symbols
        for relationship in item.relationships
        if relationship.is_implementation
    }
    assert edges, "the TypeScript fixture must carry implementation edges"

    provider = _provider(TYPESCRIPT, tmp_path)
    by_interface: dict[str, set[str]] = {}
    for implementer, interface in edges:
        by_interface.setdefault(interface, set()).add(implementer)

    for interface, implementers in sorted(by_interface.items()):
        bundle = provider.evidence_for_symbol(interface, EvidenceKind.IMPLEMENTATION)
        returned = {record.target_symbol for record in bundle.records}
        # Every implementer is returned, and the interface itself never is.
        assert returned == implementers
        assert all(record.exact for record in bundle.records)
        # The reverse direction must be empty: an implementer has no
        # implementers here, and inferring one from the shared name would be
        # exactly the name-based guess the relationship exists to replace.
        for implementer in sorted(implementers):
            reverse = provider.evidence_for_symbol(
                implementer, EvidenceKind.IMPLEMENTATION
            )
            assert reverse.records == []


@pytest.mark.parametrize("fixture", INDEXES, ids=IDS)
def test_caret_navigation_on_a_unicode_line(fixture: RealIndex, tmp_path: Path) -> None:
    """The end-to-end case: a caret on a line whose columns are UTF-16."""
    path, needle = UNICODE_LINES[fixture.name]
    provider = _provider(fixture, tmp_path)
    source = (fixture.directory / path).read_text(encoding="utf-8").splitlines()
    line_number = next(
        index for index, text in enumerate(source) if not text.isascii() and needle in text
    )
    character_column = source[line_number].index(needle)

    bundle = provider.definition(
        PrecisionQuery(path, line_number + 1, character_column + 1)
    )
    assert bundle.records, (path, line_number, character_column)
    record = bundle.records[0]
    assert record.exact
    assert record.trust is TrustTier.EXACT
    assert needle in str(record.metadata["symbol_identity"]["symbol"])

    # One column to the left is inside the Unicode text and must not resolve to
    # the identifier: that is exactly the off-by-N a missing conversion causes.
    before = provider.definition(PrecisionQuery(path, line_number + 1, 1))
    assert [item.target_symbol for item in before.records] != [record.target_symbol]


KNOWN_ROLE_BITS = int(
    SymbolRole.DEFINITION
    | SymbolRole.IMPORT
    | SymbolRole.WRITE_ACCESS
    | SymbolRole.READ_ACCESS
    | SymbolRole.GENERATED
    | SymbolRole.TEST
    | SymbolRole.FORWARD_DEFINITION
)


@pytest.mark.parametrize("fixture", INDEXES, ids=IDS)
def test_role_flags_decode_to_named_roles(fixture: RealIndex) -> None:
    seen: set[str] = set()
    for document in fixture.imported().documents:
        for occurrence in document.occurrences:
            seen.update(occurrence.role_names())
            # Every emitted bit must be a role the schema defines.
            assert occurrence.roles == occurrence.roles & KNOWN_ROLE_BITS
    assert "definition" in seen


@pytest.mark.parametrize("fixture", INDEXES, ids=IDS)
def test_a_reference_is_recognised_whether_or_not_a_read_bit_is_set(
    fixture: RealIndex,
) -> None:
    """The two pinned indexers disagree about role bits on references.

    scip-python marks a reference ``ReadAccess``; scip-typescript emits ``0``.
    Both are references, so reference lookup must key off the absence of the
    Definition bit rather than the presence of a read bit.
    """
    imported = fixture.imported()
    references = [
        occurrence
        for document in imported.documents
        for occurrence in document.occurrences
        if not occurrence.is_definition
    ]
    assert references
    for occurrence in references:
        scope = occurrence.path if occurrence.symbol.startswith("local ") else None
        assert occurrence in imported.references_for(occurrence.symbol, scope)


def test_the_two_real_indexers_use_different_reference_role_bits() -> None:
    """Pin the observed difference, so a fixture refresh that changes it is visible."""

    def reference_roles(fixture: RealIndex) -> set[int]:
        return {
            occurrence.roles
            for document in fixture.imported().documents
            for occurrence in document.occurrences
            if not occurrence.is_definition
        }

    assert int(SymbolRole.READ_ACCESS) in reference_roles(PYTHON)
    assert reference_roles(TYPESCRIPT) == {0}


# -- helpers ----------------------------------------------------------------


def _provider(fixture: RealIndex, tmp_path: Path) -> PrecisionEvidenceProvider:
    """Serve the fixture from a temporary root whose sources look freshly indexed."""
    import os
    import shutil
    import time

    root = tmp_path / fixture.name
    shutil.copytree(fixture.directory, root)
    later = time.time() + 600
    os.utime(root / "index.scip", (later, later))
    return PrecisionEvidenceProvider(root, CortexConfig(project_root=root))
